name: tauri_app_build

on:
  push:
    tags:
      - 'fix-v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - run: echo "VERSION=$(jq -r '.package.version' vue/src-tauri/tauri.conf.json)" >> "$GITHUB_ENV"
        if: matrix.os == 'ubuntu-22.04'
      - run: echo "VERSION=$(jq -r '.package.version' vue/src-tauri/tauri.conf.json)" >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: yarn install
        working-directory: vue

      - name: Build frontend dist
        run: yarn build
        working-directory: vue

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install FFmpeg
        run: choco install ffmpeg -y

      - name: Install Dependencies
        run: |
          pip install --only-binary :all: av==14.0.1
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app.py
          output-file: iib_api_server
          output-dir: out
          include-module: imageio.plugins.pyav
          include-data-dir: |
            vue/dist=vue/dist

      - run: cp out/iib_api_server out/iib_app_cli-${{ env.VERSION }}-${{ runner.os }}
        if: matrix.os == 'ubuntu-22.04'
      - run: cp out/iib_api_server.exe out/iib_app_cli-${{ env.VERSION }}-${{ runner.os }}.exe
        if: matrix.os == 'windows-latest'

      - name: Upload Server Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iib_app_cli_${{ runner.os }}
          path: |
            out/iib_app_cli-${{ env.VERSION }}-${{ runner.os }}
            out/iib_app_cli-${{ env.VERSION }}-${{ runner.os }}.exe

      - name: Upload Server Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iib_api_server-${{ env.VERSION }}-${{ runner.os }}
          path: |
            out/iib_api_server.exe
            out/iib_api_server

      - run: mv out/iib_api_server.exe vue/src-tauri/iib_api_server-x86_64-pc-windows-msvc.exe
        if: matrix.os == 'windows-latest'

      - run: mv out/iib_api_server vue/src-tauri/iib_api_server-x86_64-unknown-linux-gnu
        if: matrix.os == 'ubuntu-22.04'

      # - name: Install frontend dependencies
      #   run: yarn install
      #   working-directory: vue

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './vue/src-tauri -> target'

      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Build the app
        run: |
          yarn tauri-build
        working-directory: vue


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ env.VERSION }}-${{ runner.os }}
          path: |
            vue/src-tauri/target/release/bundle/nsis/Infinite Image Browsing_${{ env.VERSION }}_x64-setup.exe
